package com.trustabac.iot.entity;

/**
 * Authoritative authorization decision generated by the smart contract.
 */
public enum Decision {
    DENY,      // 0
    RESTRICT,  // 1
    ALLOW;     // 2

    public static Decision fromSolidityCode(int code) {
        return switch (code) {
            case 0 -> DENY;
            case 1 -> RESTRICT;
            case 2 -> ALLOW;
            default -> throw new IllegalArgumentException("Unknown Solidity Decision code: " + code);
        };
    }
}
